package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * CatClasificacion generated by hbm2java
 */
@Entity
@Table(name="cat_clasificacion"
    ,catalog="dbakihabara"
)
public class CatClasificacion  implements java.io.Serializable {


     private int idClasificacion;
     private String clasificacion;
     private String descripcion;
     private Set<Game> games = new HashSet<Game>(0);

    public CatClasificacion() {
    }

	
    public CatClasificacion(int idClasificacion, String clasificacion) {
        this.idClasificacion = idClasificacion;
        this.clasificacion = clasificacion;
    }
    public CatClasificacion(int idClasificacion, String clasificacion, String descripcion, Set<Game> games) {
       this.idClasificacion = idClasificacion;
       this.clasificacion = clasificacion;
       this.descripcion = descripcion;
       this.games = games;
    }
   
     @Id 
    
    @Column(name="idClasificacion", unique=true, nullable=false)
    public int getIdClasificacion() {
        return this.idClasificacion;
    }
    
    public void setIdClasificacion(int idClasificacion) {
        this.idClasificacion = idClasificacion;
    }
    
    @Column(name="clasificacion", nullable=false, length=45)
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catClasificacions")
    public Set<Game> getGames() {
        return this.games;
    }
    
    public void setGames(Set<Game> games) {
        this.games = games;
    }




}


