package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * CatCategoria generated by hbm2java
 */
@Entity
@Table(name="cat_categoria"
    ,catalog="dbakihabara"
)
public class CatCategoria  implements java.io.Serializable {


     private int idCategoria;
     private String categoria;
     private String descripcion;
     private Set<Game> games = new HashSet<Game>(0);

    public CatCategoria() {
    }

	
    public CatCategoria(int idCategoria, String categoria) {
        this.idCategoria = idCategoria;
        this.categoria = categoria;
    }
    public CatCategoria(int idCategoria, String categoria, String descripcion, Set<Game> games) {
       this.idCategoria = idCategoria;
       this.categoria = categoria;
       this.descripcion = descripcion;
       this.games = games;
    }
   
     @Id 
    
    @Column(name="idCategoria", unique=true, nullable=false)
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    
    @Column(name="categoria", nullable=false, length=45)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="gamecategoria", catalog="dbakihabara", joinColumns = { 
        @JoinColumn(name="idCategoria", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idgameR", nullable=false, updatable=false) })
    public Set<Game> getGames() {
        return this.games;
    }
    
    public void setGames(Set<Game> games) {
        this.games = games;
    }




}


