package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatEstadoVenta generated by hbm2java
 */
@Entity
@Table(name="cat_estado_venta"
    ,catalog="dbakihabara"
)
public class CatEstadoVenta  implements java.io.Serializable {


     private String idEstadoVenta;
     private String descripcion;
     private Set<Venta> ventas = new HashSet<Venta>(0);
     private Set<Venta> ventas_1 = new HashSet<Venta>(0);

    public CatEstadoVenta() {
    }

	
    public CatEstadoVenta(String idEstadoVenta, String descripcion) {
        this.idEstadoVenta = idEstadoVenta;
        this.descripcion = descripcion;
    }
    public CatEstadoVenta(String idEstadoVenta, String descripcion, Set<Venta> ventas, Set<Venta> ventas_1) {
       this.idEstadoVenta = idEstadoVenta;
       this.descripcion = descripcion;
       this.ventas = ventas;
       this.ventas_1 = ventas_1;
    }
   
     @Id 
    
    @Column(name="idEstadoVenta", unique=true, nullable=false, length=45)
    public String getIdEstadoVenta() {
        return this.idEstadoVenta;
    }
    
    public void setIdEstadoVenta(String idEstadoVenta) {
        this.idEstadoVenta = idEstadoVenta;
    }
    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catEstadoVenta")
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catEstadoVenta")
    public Set<Venta> getVentas_1() {
        return this.ventas_1;
    }
    
    public void setVentas_1(Set<Venta> ventas_1) {
        this.ventas_1 = ventas_1;
    }




}


