package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatPuestos generated by hbm2java
 */
@Entity
@Table(name="cat_puestos"
    ,catalog="dbakihabara"
)
public class CatPuestos  implements java.io.Serializable {


     private String puesto;
     private String descripcion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Empleado> empleados_1 = new HashSet<Empleado>(0);

    public CatPuestos() {
    }

	
    public CatPuestos(String puesto) {
        this.puesto = puesto;
    }
    public CatPuestos(String puesto, String descripcion, Set<Empleado> empleados, Set<Empleado> empleados_1) {
       this.puesto = puesto;
       this.descripcion = descripcion;
       this.empleados = empleados;
       this.empleados_1 = empleados_1;
    }
   
     @Id 
    
    @Column(name="puesto", unique=true, nullable=false, length=45)
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catPuestos")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catPuestos")
    public Set<Empleado> getEmpleados_1() {
        return this.empleados_1;
    }
    
    public void setEmpleados_1(Set<Empleado> empleados_1) {
        this.empleados_1 = empleados_1;
    }




}


