package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatRoles generated by hbm2java
 */
@Entity
@Table(name="cat_roles"
    ,catalog="dbakihabara"
)
public class CatRoles  implements java.io.Serializable {


     private String rol;
     private String descripcionRol;
     private Set<Rolesusarios> rolesusarioses = new HashSet<Rolesusarios>(0);
     private Set<Rolesusarios> rolesusarioses_1 = new HashSet<Rolesusarios>(0);

    public CatRoles() {
    }

	
    public CatRoles(String rol) {
        this.rol = rol;
    }
    public CatRoles(String rol, String descripcionRol, Set<Rolesusarios> rolesusarioses, Set<Rolesusarios> rolesusarioses_1) {
       this.rol = rol;
       this.descripcionRol = descripcionRol;
       this.rolesusarioses = rolesusarioses;
       this.rolesusarioses_1 = rolesusarioses_1;
    }
   
     @Id 
    
    @Column(name="rol", unique=true, nullable=false, length=30)
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    
    @Column(name="descripcion_rol", length=45)
    public String getDescripcionRol() {
        return this.descripcionRol;
    }
    
    public void setDescripcionRol(String descripcionRol) {
        this.descripcionRol = descripcionRol;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catRoles")
    public Set<Rolesusarios> getRolesusarioses() {
        return this.rolesusarioses;
    }
    
    public void setRolesusarioses(Set<Rolesusarios> rolesusarioses) {
        this.rolesusarioses = rolesusarioses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="catRoles")
    public Set<Rolesusarios> getRolesusarioses_1() {
        return this.rolesusarioses_1;
    }
    
    public void setRolesusarioses_1(Set<Rolesusarios> rolesusarioses_1) {
        this.rolesusarioses_1 = rolesusarioses_1;
    }




}


