package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="dbakihabara"
)
public class Cliente  implements java.io.Serializable {


     private int idClienteR;
     private Persona persona;
     private Date fechaAlta;
     private String password;
     private Set<Venta> ventas = new HashSet<Venta>(0);
     private Set<Venta> ventas_1 = new HashSet<Venta>(0);

    public Cliente() {
    }

	
    public Cliente(int idClienteR, Persona persona, Date fechaAlta) {
        this.idClienteR = idClienteR;
        this.persona = persona;
        this.fechaAlta = fechaAlta;
    }
    public Cliente(int idClienteR, Persona persona, Date fechaAlta, String password, Set<Venta> ventas, Set<Venta> ventas_1) {
       this.idClienteR = idClienteR;
       this.persona = persona;
       this.fechaAlta = fechaAlta;
       this.password = password;
       this.ventas = ventas;
       this.ventas_1 = ventas_1;
    }
   
     @Id 
    
    @Column(name="idClienteR", unique=true, nullable=false)
    public int getIdClienteR() {
        return this.idClienteR;
    }
    
    public void setIdClienteR(int idClienteR) {
        this.idClienteR = idClienteR;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idClienteR", unique=true, nullable=false, insertable=false, updatable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaAlta", nullable=false, length=10)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Venta> getVentas_1() {
        return this.ventas_1;
    }
    
    public void setVentas_1(Set<Venta> ventas_1) {
        this.ventas_1 = ventas_1;
    }




}


