package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="dbakihabara"
)
public class Compra  implements java.io.Serializable {


     private Integer idCompraR;
     private Proveedor proveedor;
     private Empleado empleado;
     private Date fechaCompra;
     private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);
     private Set<DetalleCompra> detalleCompras_1 = new HashSet<DetalleCompra>(0);

    public Compra() {
    }

	
    public Compra(Proveedor proveedor, Empleado empleado, Date fechaCompra) {
        this.proveedor = proveedor;
        this.empleado = empleado;
        this.fechaCompra = fechaCompra;
    }
    public Compra(Proveedor proveedor, Empleado empleado, Date fechaCompra, Set<DetalleCompra> detalleCompras, Set<DetalleCompra> detalleCompras_1) {
       this.proveedor = proveedor;
       this.empleado = empleado;
       this.fechaCompra = fechaCompra;
       this.detalleCompras = detalleCompras;
       this.detalleCompras_1 = detalleCompras_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCompraR", unique=true, nullable=false)
    public Integer getIdCompraR() {
        return this.idCompraR;
    }
    
    public void setIdCompraR(Integer idCompraR) {
        this.idCompraR = idCompraR;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCompra", nullable=false, length=19)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compra")
    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compra")
    public Set<DetalleCompra> getDetalleCompras_1() {
        return this.detalleCompras_1;
    }
    
    public void setDetalleCompras_1(Set<DetalleCompra> detalleCompras_1) {
        this.detalleCompras_1 = detalleCompras_1;
    }




}


