package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleVenta generated by hbm2java
 */
@Entity
@Table(name="detalle_venta"
    ,catalog="dbakihabara"
)
public class DetalleVenta  implements java.io.Serializable {


     private DetalleVentaId id;
     private Game game;
     private Venta venta;
     private int cantidad;
     private double precioVenta;
     private double descuento;

    public DetalleVenta() {
    }

    public DetalleVenta(DetalleVentaId id, Game game, Venta venta, int cantidad, double precioVenta, double descuento) {
       this.id = id;
       this.game = game;
       this.venta = venta;
       this.cantidad = cantidad;
       this.precioVenta = precioVenta;
       this.descuento = descuento;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idVentaR", column=@Column(name="idVentaR", nullable=false) ), 
        @AttributeOverride(name="idGameR", column=@Column(name="idGameR", nullable=false) ) } )
    public DetalleVentaId getId() {
        return this.id;
    }
    
    public void setId(DetalleVentaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGameR", nullable=false, insertable=false, updatable=false)
    public Game getGame() {
        return this.game;
    }
    
    public void setGame(Game game) {
        this.game = game;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVentaR", nullable=false, insertable=false, updatable=false)
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="precioVenta", nullable=false, precision=22, scale=0)
    public double getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(double precioVenta) {
        this.precioVenta = precioVenta;
    }
    
    @Column(name="descuento", nullable=false, precision=22, scale=0)
    public double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(double descuento) {
        this.descuento = descuento;
    }




}


