package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleVentaId generated by hbm2java
 */
@Embeddable
public class DetalleVentaId  implements java.io.Serializable {


     private int idVentaR;
     private int idGameR;

    public DetalleVentaId() {
    }

    public DetalleVentaId(int idVentaR, int idGameR) {
       this.idVentaR = idVentaR;
       this.idGameR = idGameR;
    }
   

    @Column(name="idVentaR", nullable=false)
    public int getIdVentaR() {
        return this.idVentaR;
    }
    
    public void setIdVentaR(int idVentaR) {
        this.idVentaR = idVentaR;
    }

    @Column(name="idGameR", nullable=false)
    public int getIdGameR() {
        return this.idGameR;
    }
    
    public void setIdGameR(int idGameR) {
        this.idGameR = idGameR;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleVentaId) ) return false;
		 DetalleVentaId castOther = ( DetalleVentaId ) other; 
         
		 return (this.getIdVentaR()==castOther.getIdVentaR())
 && (this.getIdGameR()==castOther.getIdGameR());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVentaR();
         result = 37 * result + this.getIdGameR();
         return result;
   }   


}


