package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleCompra generated by hbm2java
 */
@Entity
@Table(name="detalle_compra"
    ,catalog="dbakihabara"
)
public class DetalleCompra  implements java.io.Serializable {


     private DetalleCompraId id;
     private Game game;
     private Compra compra;
     private double precioCompra;
     private double precioVenta;
     private Integer cantidad;
     private Integer descuentoC;

    public DetalleCompra() {
    }

	
    public DetalleCompra(DetalleCompraId id, Game game, Compra compra, double precioCompra, double precioVenta) {
        this.id = id;
        this.game = game;
        this.compra = compra;
        this.precioCompra = precioCompra;
        this.precioVenta = precioVenta;
    }
    public DetalleCompra(DetalleCompraId id, Game game, Compra compra, double precioCompra, double precioVenta, Integer cantidad, Integer descuentoC) {
       this.id = id;
       this.game = game;
       this.compra = compra;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
       this.cantidad = cantidad;
       this.descuentoC = descuentoC;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idCompraR", column=@Column(name="idCompraR", nullable=false) ), 
        @AttributeOverride(name="idGameR", column=@Column(name="idGameR", nullable=false) ) } )
    public DetalleCompraId getId() {
        return this.id;
    }
    
    public void setId(DetalleCompraId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGameR", nullable=false, insertable=false, updatable=false)
    public Game getGame() {
        return this.game;
    }
    
    public void setGame(Game game) {
        this.game = game;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCompraR", nullable=false, insertable=false, updatable=false)
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    
    @Column(name="precioCompra", nullable=false, precision=22, scale=0)
    public double getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(double precioCompra) {
        this.precioCompra = precioCompra;
    }
    
    @Column(name="precioVenta", nullable=false, precision=22, scale=0)
    public double getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(double precioVenta) {
        this.precioVenta = precioVenta;
    }
    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="descuentoC")
    public Integer getDescuentoC() {
        return this.descuentoC;
    }
    
    public void setDescuentoC(Integer descuentoC) {
        this.descuentoC = descuentoC;
    }




}


