package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Direccion generated by hbm2java
 */
@Entity
@Table(name="direccion"
    ,catalog="dbakihabara"
)
public class Direccion  implements java.io.Serializable {


     private Integer idDireccion;
     private String estado;
     private String ciudad;
     private String cp;
     private String col;
     private String calle;
     private String numero;
     private String descripcion;
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Persona> personas_1 = new HashSet<Persona>(0);

    public Direccion() {
    }

	
    public Direccion(String estado, String ciudad, String cp, String col, String calle, String numero) {
        this.estado = estado;
        this.ciudad = ciudad;
        this.cp = cp;
        this.col = col;
        this.calle = calle;
        this.numero = numero;
    }
    public Direccion(String estado, String ciudad, String cp, String col, String calle, String numero, String descripcion, Set<Persona> personas, Set<Persona> personas_1) {
       this.estado = estado;
       this.ciudad = ciudad;
       this.cp = cp;
       this.col = col;
       this.calle = calle;
       this.numero = numero;
       this.descripcion = descripcion;
       this.personas = personas;
       this.personas_1 = personas_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idDireccion", unique=true, nullable=false)
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    
    @Column(name="estado", nullable=false, length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="ciudad", nullable=false, length=45)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    
    @Column(name="cp", nullable=false, length=18)
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    
    @Column(name="col", nullable=false, length=45)
    public String getCol() {
        return this.col;
    }
    
    public void setCol(String col) {
        this.col = col;
    }
    
    @Column(name="calle", nullable=false, length=45)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    
    @Column(name="numero", nullable=false, length=8)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="direccion")
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="direccion")
    public Set<Persona> getPersonas_1() {
        return this.personas_1;
    }
    
    public void setPersonas_1(Set<Persona> personas_1) {
        this.personas_1 = personas_1;
    }




}


