package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Estudio generated by hbm2java
 */
@Entity
@Table(name="estudio"
    ,catalog="dbakihabara"
)
public class Estudio  implements java.io.Serializable {


     private Integer idEstudio;
     private String nombre;
     private String resenia;
     private Set<Game> games = new HashSet<Game>(0);

    public Estudio() {
    }

	
    public Estudio(String nombre) {
        this.nombre = nombre;
    }
    public Estudio(String nombre, String resenia, Set<Game> games) {
       this.nombre = nombre;
       this.resenia = resenia;
       this.games = games;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idEstudio", unique=true, nullable=false)
    public Integer getIdEstudio() {
        return this.idEstudio;
    }
    
    public void setIdEstudio(Integer idEstudio) {
        this.idEstudio = idEstudio;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="resenia", length=65535)
    public String getResenia() {
        return this.resenia;
    }
    
    public void setResenia(String resenia) {
        this.resenia = resenia;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="gameestudio", catalog="dbakihabara", joinColumns = { 
        @JoinColumn(name="idestudioR", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idgameR", nullable=false, updatable=false) })
    public Set<Game> getGames() {
        return this.games;
    }
    
    public void setGames(Set<Game> games) {
        this.games = games;
    }




}


