package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,catalog="dbakihabara"
)
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String razonSocial;
     private Set<Compra> compras = new HashSet<Compra>(0);
     private Set<Compra> compras_1 = new HashSet<Compra>(0);

    public Proveedor() {
    }

	
    public Proveedor(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public Proveedor(String razonSocial, Set<Compra> compras, Set<Compra> compras_1) {
       this.razonSocial = razonSocial;
       this.compras = compras;
       this.compras_1 = compras_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idProveedor", unique=true, nullable=false)
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    
    @Column(name="RazonSocial", nullable=false, length=70)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Compra> getCompras_1() {
        return this.compras_1;
    }
    
    public void setCompras_1(Set<Compra> compras_1) {
        this.compras_1 = compras_1;
    }




}


