package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolesusariosId generated by hbm2java
 */
@Embeddable
public class RolesusariosId  implements java.io.Serializable {


     private String rolR;
     private int idUsuario;

    public RolesusariosId() {
    }

    public RolesusariosId(String rolR, int idUsuario) {
       this.rolR = rolR;
       this.idUsuario = idUsuario;
    }
   

    @Column(name="rolR", nullable=false, length=30)
    public String getRolR() {
        return this.rolR;
    }
    
    public void setRolR(String rolR) {
        this.rolR = rolR;
    }

    @Column(name="idUsuario", nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolesusariosId) ) return false;
		 RolesusariosId castOther = ( RolesusariosId ) other; 
         
		 return ( (this.getRolR()==castOther.getRolR()) || ( this.getRolR()!=null && castOther.getRolR()!=null && this.getRolR().equals(castOther.getRolR()) ) )
 && (this.getIdUsuario()==castOther.getIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRolR() == null ? 0 : this.getRolR().hashCode() );
         result = 37 * result + this.getIdUsuario();
         return result;
   }   


}


