package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rolesusarios generated by hbm2java
 */
@Entity
@Table(name="rolesusarios"
    ,catalog="dbakihabara"
    , uniqueConstraints = @UniqueConstraint(columnNames="usuario") 
)
public class Rolesusarios  implements java.io.Serializable {


     private RolesusariosId id;
     private Persona persona;
     private CatRoles catRoles;
     private String password;
     private String usuario;

    public Rolesusarios() {
    }

    public Rolesusarios(RolesusariosId id, Persona persona, CatRoles catRoles, String password, String usuario) {
       this.id = id;
       this.persona = persona;
       this.catRoles = catRoles;
       this.password = password;
       this.usuario = usuario;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="rolR", column=@Column(name="rolR", nullable=false, length=30) ), 
        @AttributeOverride(name="idUsuario", column=@Column(name="idUsuario", nullable=false) ) } )
    public RolesusariosId getId() {
        return this.id;
    }
    
    public void setId(RolesusariosId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false, insertable=false, updatable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rolR", nullable=false, insertable=false, updatable=false)
    public CatRoles getCatRoles() {
        return this.catRoles;
    }
    
    public void setCatRoles(CatRoles catRoles) {
        this.catRoles = catRoles;
    }
    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="usuario", unique=true, nullable=false, length=15)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }




}


