package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="sucursal"
    ,catalog="dbakihabara"
)
public class Sucursal  implements java.io.Serializable {


     private int idSucursal;
     private String nombre;
     private int direccion;
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);
     private Set<Departamento> departamentos_1 = new HashSet<Departamento>(0);

    public Sucursal() {
    }

	
    public Sucursal(int idSucursal, String nombre, int direccion) {
        this.idSucursal = idSucursal;
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Sucursal(int idSucursal, String nombre, int direccion, Set<Departamento> departamentos, Set<Departamento> departamentos_1) {
       this.idSucursal = idSucursal;
       this.nombre = nombre;
       this.direccion = direccion;
       this.departamentos = departamentos;
       this.departamentos_1 = departamentos_1;
    }
   
     @Id 
    
    @Column(name="idSUCURSAL", unique=true, nullable=false)
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="direccion", nullable=false)
    public int getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(int direccion) {
        this.direccion = direccion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sucursal")
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sucursal")
    public Set<Departamento> getDepartamentos_1() {
        return this.departamentos_1;
    }
    
    public void setDepartamentos_1(Set<Departamento> departamentos_1) {
        this.departamentos_1 = departamentos_1;
    }




}


