package modelo;
// Generated 25/04/2013 10:50:31 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="venta"
    ,catalog="dbakihabara"
)
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Empleado empleado;
     private CatEstadoVenta catEstadoVenta;
     private Cliente cliente;
     private Date fechaPedido;
     private Date fechaentrega;
     private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);
     private Set<DetalleVenta> detalleVentas_1 = new HashSet<DetalleVenta>(0);

    public Venta() {
    }

	
    public Venta(Empleado empleado, CatEstadoVenta catEstadoVenta, Cliente cliente, Date fechaPedido, Date fechaentrega) {
        this.empleado = empleado;
        this.catEstadoVenta = catEstadoVenta;
        this.cliente = cliente;
        this.fechaPedido = fechaPedido;
        this.fechaentrega = fechaentrega;
    }
    public Venta(Empleado empleado, CatEstadoVenta catEstadoVenta, Cliente cliente, Date fechaPedido, Date fechaentrega, Set<DetalleVenta> detalleVentas, Set<DetalleVenta> detalleVentas_1) {
       this.empleado = empleado;
       this.catEstadoVenta = catEstadoVenta;
       this.cliente = cliente;
       this.fechaPedido = fechaPedido;
       this.fechaentrega = fechaentrega;
       this.detalleVentas = detalleVentas;
       this.detalleVentas_1 = detalleVentas_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idVENTA", unique=true, nullable=false)
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEmpleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoR", nullable=false)
    public CatEstadoVenta getCatEstadoVenta() {
        return this.catEstadoVenta;
    }
    
    public void setCatEstadoVenta(CatEstadoVenta catEstadoVenta) {
        this.catEstadoVenta = catEstadoVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaPedido", nullable=false, length=19)
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaentrega", nullable=false, length=10)
    public Date getFechaentrega() {
        return this.fechaentrega;
    }
    
    public void setFechaentrega(Date fechaentrega) {
        this.fechaentrega = fechaentrega;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="venta")
    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="venta")
    public Set<DetalleVenta> getDetalleVentas_1() {
        return this.detalleVentas_1;
    }
    
    public void setDetalleVentas_1(Set<DetalleVenta> detalleVentas_1) {
        this.detalleVentas_1 = detalleVentas_1;
    }




}


